### ISSUE TITLE
Waterfox-classic fails to build with rust-1.40

### ISSUE THREAD

**Issue by Polynomial-C** [MrAlex94/Waterfox#1315]
```
   Compiling encoding_glue v0.1.0 (/var/tmp/portage/www-client/waterfox-2019.12/work/Waterfox-2019.12-classic/intl/encoding_glue)
error[E0713]: borrow may still be in use when destructor runs
   --> /var/tmp/portage/www-client/waterfox-2019.12/work/Waterfox-2019.12-classic/third_party/rust/url/src/form_urlencoded.rs:248:40
    |
246 | impl<'a> Target for ::UrlQuery<'a> {
    |      -- lifetime `'a` defined here
247 |     fn as_mut_string(&mut self) -> &mut String { &mut self.url.serialization }
248 |     fn finish(self) -> &'a mut ::Url { self.url }
    |                                        ^^^^^^^^ - here, drop of `self` needs exclusive access to `*self.url`, because the type `UrlQuery<'_>` implements the `Drop` trait
    |                                        |
    |                                        returning this value requires that `*self.url` is borrowed for `'a`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0713`.
error: could not compile `url`.
warning: build failed, waiting for other jobs to finish...
error: build failed
make[4]: *** [/var/tmp/portage/www-client/waterfox-2019.12/work/Waterfox-2019.12-classic/config/rules.mk:998: force-cargo-library-build] Error 101
```

**Comment by Polynomial-C** [comment]
Caused by the following merged rust PR:
https://github.com/rust-lang/rust/pull/64221/ (NLL warnings in the 2015 edition are now hard errors)

**Comment by hawkeye116477** [comment]
If this issue is solved, then it can be probably closed :smile:

**Comment by Polynomial-C** [comment]
Indeed. No that we have a release that builds with rust-1.40 this can be closed.
