### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'read' on FreeBSD

### ISSUE THREAD

**Issue by Martinfx** [MrAlex94/Waterfox#3648]
### What happened?

Hi,
i am a maintainer Waterfox on FreeBSD and i have a problem with the 6.5.2 version. 
I  tried to build on 14.2 FreeBSD with poudriere.

```
js/src> checking whether /usr/local/bin/clang++17 accepts -g... (cached) yes
js/src> checking whether the linker supports Identical Code Folding... (cached) yes
js/src> checking whether removing dead symbols breaks debugging... (cached) no
js/src> checking for valid optimization flags... yes
js/src> creating ./config.data
Creating config.status
Reticulating splines...
Traceback (most recent call last):
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/sandbox.py", line 155, in exec_file
    source = six.ensure_text(self._finder.get(path).read())
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'read'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/reader.py", line 1111, in read_mozbuild
    for s in self._read_mozbuild(
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/reader.py", line 1185, in _read_mozbuild
    sandbox.exec_file(path)
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/reader.py", line 227, in exec_file
    Sandbox.exec_file(self, path, becomes_current_path)
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/sandbox.py", line 157, in exec_file
    raise SandboxLoadError(
mozbuild.frontend.sandbox.SandboxLoadError: ([], <traceback object at 0x2faffc081c00>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/configure.py", line 351, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/configure.py", line 176, in main
    return config_status(config)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/configure.py", line 300, in config_status
    return config_status(args=[], **sanitized_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/config_status.py", line 201, in config_status
    pool = BackendPool(definitions, processes=processes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/config_status.py", line 54, in __init__
    definitions = list(definitions)
                  ^^^^^^^^^^^^^^^^^
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/emitter.py", line 144, in emit
    for out in output:
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/reader.py", line 906, in read_topsrcdir
    for r in self.read_mozbuild(path, self.config):
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/reader.py", line 1117, in read_mozbuild
    raise bre
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/reader.py", line 1111, in read_mozbuild
    for s in self._read_mozbuild(
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/reader.py", line 1289, in _read_mozbuild
    for res in self.read_mozbuild(
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/reader.py", line 1117, in read_mozbuild
    raise bre
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/reader.py", line 1111, in read_mozbuild
    for s in self._read_mozbuild(
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/reader.py", line 1289, in _read_mozbuild
    for res in self.read_mozbuild(
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/reader.py", line 1117, in read_mozbuild
    raise bre
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/reader.py", line 1111, in read_mozbuild
    for s in self._read_mozbuild(
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/reader.py", line 1289, in _read_mozbuild
    for res in self.read_mozbuild(
  File "/wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/python/mozbuild/mozbuild/frontend/reader.py", line 1130, in read_mozbuild
    raise BuildReaderError(
mozbuild.frontend.reader.BuildReaderError: 
==============================
FATAL ERROR PROCESSING MOZBUILD FILE
==============================

The error occurred while processing the following file:

    /wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/waterfox/browser/moz.build

The underlying problem is we referenced a path that does not exist. That path is:

    /wrkdirs/usr/ports/www/waterfox/work/Waterfox-6.5.2/waterfox/browser/locales/moz.build

Either create the file if it needs to exist or do not reference it.

===>  Script "configure" failed unexpectedly.
Please report the problem to freebsd@sysctl.cz [maintainer] and attach the
"/wrkdirs/usr/ports/www/waterfox/work/.build/config.log" including the output
of the failure of your make command. Also, it might be a good idea to provide
an overview of all packages installed on your system (e.g. a
/usr/local/sbin/pkg-static info -g -Ea).
*** Error code 1


```

### Reproducible?

- [ ] I have checked that this issue cannot be reproduced on Mozilla Firefox.

### Version

Other

### What platform are you seeing the problem on?

FreeBSD

### Relevant log output

```shell

```

**Comment by Martinfx** [comment]
there is submodule. Fixed in waterfox freebsd Makefile.
